name: CD

on:
  workflow_run:
    workflows:
      - CI
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push'}}
    name: Deploy Static Website
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-version: ['8.3']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring
          tools: composer

      - name: Display PHP version
        run: php -v

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install Node.js dependencies
        run: npm install

      - name: Build with Vite
        run: npm run build

      - name: Start PHP server
        run: php -d display_errors=1 -d log_errors=1 -d error_reporting=E_ALL -d error_log=/tmp/php_errors.log -S 127.0.0.1:9000 public/index.php &

      - name: Download static HTML with wget
        run: |
          mkdir -p output
          wget --mirror --convert-links --adjust-extension \
               --page-requisites --no-parent \
               --directory-prefix=output --no-host-directories \
               --restrict-file-names=windows \
               http://127.0.0.1:9000/ || [[ $? == 8 ]]

      - name: Show PHP error log
        run: cat /tmp/php_errors.log || true

      - name: Fail if output directory is missing or empty and debug HTTP response
        run: |
          if [ ! -d "output" ] || [ -z "$(ls -A output)" ]; then
            curl -v http://127.0.0.1:9000/
            echo "Error: output directory is missing or empty."
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: output
